# Project: 项目1
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = 未命名4.o
LINKOBJ  = 未命名4.o
LIBS     = -L"D:/ProgramFils/Dev-Cpp/MinGW64/lib" -L"D:/ProgramFils/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc
INCS     = -I"D:/ProgramFils/Dev-Cpp/MinGW64/include" -I"D:/ProgramFils/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"D:/ProgramFils/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"D:/ProgramFils/Dev-Cpp/MinGW64/include" -I"D:/ProgramFils/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"D:/ProgramFils/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"D:/ProgramFils/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = 6.exe
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

未命名4.o: 未命名4.cpp
	$(CPP) -c 未命名4.cpp -o 未命名4.o $(CXXFLAGS)
